# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPfiknaYK-lSIvCL2oSN44AuQU-eSRuM
"""

import streamlit as st
import pandas as pd

st.image("BSF.jpeg")
st.title("PubMed MeSH Terms Dashboard")

# Load data (uploaded CSV)
df = pd.read_csv("mesh_counts.csv")

# Sort (if not already sorted)
df = df.sort_values(by="Count", ascending=False)

# Slider
top_n = st.slider("Top N terms", 5, 100, 20)

df_top = df.head(top_n)

# Chart
st.bar_chart(df_top.set_index("MeSH Term"))

# Table
st.dataframe(df_top)

# Search
df2 = pd.read_csv("pubmed_batched_results.csv")
df_expanded = df2.dropna(subset=["MeSH Terms"]).copy()
df_expanded["MeSH Terms"] = df_expanded["MeSH Terms"].str.split(";")

df_expanded = df_expanded.explode("MeSH Terms")
df_expanded["MeSH Terms"] = df_expanded["MeSH Terms"].str.strip()

search = st.text_input("Search term")

if search:
    filtered_terms = df_expanded[
        df_expanded["MeSH Terms"].str.contains(search, case=False)
    ]

    st.subheader("Matching articles")
    st.dataframe(filtered_terms)

terms = sorted(df_expanded["MeSH Terms"].unique())
selected_term = st.selectbox("Select MeSH term", terms)

term_data = df_expanded[df_expanded["MeSH Terms"] == selected_term]

trend = (
    term_data.groupby("Year")
    .size()
    .reset_index(name="Count")
    .sort_values("Year")
)

st.line_chart(trend.set_index("Year"))
