# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPfiknaYK-lSIvCL2oSN44AuQU-eSRuM
"""

import streamlit as st
import pandas as pd

st.image("BSF.jpg")
st.title("PubMed MeSH Terms Dashboard")

# Load data (uploaded CSV)
df = pd.read_csv("mesh_counts.csv")

# Sort (if not already sorted)
df = df.sort_values(by="Count", ascending=False)

# Slider
top_n = st.slider("Top N terms", 5, 100, 20)

df_top = df.head(top_n)

# Chart
st.bar_chart(df_top.set_index("MeSH Term"))

# Table
st.dataframe(df_top)

# Search
search = st.text_input("Search term")
if search:
    st.dataframe(df[df["MeSH Term"].str.contains(search, case=False)])
